"""init request_logs

Revision ID: 2cf1ea5432da
Revises: 30f0ab8d1312
Create Date: 2024-01-15 11:16:29.419688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cf1ea5432da'
down_revision: Union[str, None] = '30f0ab8d1312'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request_logs', 'user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request_logs', sa.Column('user', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
